CREATE TABLE IF NOT EXISTS `metadata_table` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `ds_id` BIGINT(20) DEFAULT NULL COMMENT '数据源ID',
    `ds_name` VARCHAR(100) DEFAULT NULL COMMENT '数据源名称',
    `ds_code` VARCHAR(50) DEFAULT NULL COMMENT '数据源编码',
    `table_name` VARCHAR(200) NOT NULL COMMENT '物理表名',
    `table_alias` VARCHAR(200) DEFAULT NULL COMMENT '表别名',
    `table_comment` VARCHAR(1000) DEFAULT NULL COMMENT '表注释',
    `table_type` VARCHAR(30) DEFAULT 'TABLE' COMMENT '表类型',
    `data_layer` VARCHAR(20) DEFAULT NULL COMMENT '数仓分层',
    `data_domain` VARCHAR(50) DEFAULT NULL COMMENT '数据域',
    `row_count` BIGINT(20) DEFAULT NULL COMMENT '行数',
    `storage_bytes` BIGINT(20) DEFAULT NULL COMMENT '存储大小',
    `source_update_time` DATETIME DEFAULT NULL COMMENT '源表最后更新时间',
    `sensitivity_level` VARCHAR(20) DEFAULT 'NORMAL' COMMENT '敏感等级',
    `owner_id` BIGINT(20) DEFAULT NULL COMMENT '负责人ID',
    `dept_id` BIGINT(20) DEFAULT NULL COMMENT '部门ID',
    `catalog_id` BIGINT(20) DEFAULT NULL COMMENT '资产目录ID',
    `tags` VARCHAR(500) DEFAULT NULL COMMENT '标签',
    `last_scan_time` DATETIME DEFAULT NULL COMMENT '最后扫描时间',
    `status` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态',
    `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ds_table` (`tenant_id`, `ds_id`, `table_name`),
    KEY `idx_ds_id` (`ds_id`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_last_scan_time` (`last_scan_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据表';

CREATE TABLE IF NOT EXISTS `metadata_column` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `table_id` BIGINT(20) NOT NULL COMMENT '元数据表ID',
    `ds_id` BIGINT(20) DEFAULT NULL COMMENT '数据源ID',
    `table_name` VARCHAR(200) DEFAULT NULL COMMENT '表名',
    `column_name` VARCHAR(100) NOT NULL COMMENT '字段名',
    `column_alias` VARCHAR(200) DEFAULT NULL COMMENT '字段别名',
    `column_comment` VARCHAR(500) DEFAULT NULL COMMENT '字段注释',
    `data_type` VARCHAR(50) DEFAULT NULL COMMENT '数据类型',
    `is_nullable` VARCHAR(10) DEFAULT 'YES' COMMENT '是否可空',
    `column_key` VARCHAR(10) DEFAULT NULL COMMENT '键类型',
    `default_value` VARCHAR(500) DEFAULT NULL COMMENT '默认值',
    `is_primary_key` TINYINT(1) DEFAULT 0 COMMENT '是否主键',
    `is_foreign_key` TINYINT(1) DEFAULT 0 COMMENT '是否外键',
    `fk_reference` VARCHAR(200) DEFAULT NULL COMMENT '外键引用',
    `is_sensitive` TINYINT(1) DEFAULT 0 COMMENT '是否敏感字段',
    `sensitivity_level` VARCHAR(20) DEFAULT 'NORMAL' COMMENT '敏感等级',
    `sort_order` INT(11) DEFAULT 0 COMMENT '字段排序',
    `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ds_table_column` (`tenant_id`, `ds_id`, `table_name`, `column_name`),
    KEY `idx_table_id` (`table_id`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据字段';

CREATE TABLE IF NOT EXISTS `metadata_catalog` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `catalog_name` VARCHAR(100) NOT NULL COMMENT '目录名称',
    `catalog_code` VARCHAR(50) DEFAULT NULL COMMENT '目录编码',
    `catalog_type` VARCHAR(20) NOT NULL COMMENT '目录类型',
    `parent_id` BIGINT(20) DEFAULT 0 COMMENT '父目录ID',
    `sort_order` INT(11) DEFAULT 0 COMMENT '排序号',
    `status` VARCHAR(20) DEFAULT '0' COMMENT '状态 0=正常 1=停用',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产目录';

CREATE TABLE IF NOT EXISTS `data_domain` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `domain_name` VARCHAR(100) NOT NULL COMMENT '数据域名称',
    `domain_code` VARCHAR(50) DEFAULT NULL COMMENT '数据域编码',
    `domain_desc` VARCHAR(500) DEFAULT NULL COMMENT '数据域描述',
    `owner_id` BIGINT(20) DEFAULT NULL COMMENT '负责人ID',
    `dept_id` BIGINT(20) DEFAULT NULL COMMENT '部门ID',
    `status` VARCHAR(20) DEFAULT '0' COMMENT '状态 0=正常 1=停用',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` CHAR(1) DEFAULT '0' COMMENT '删除标志',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_domain_code` (`domain_code`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据域';

CREATE TABLE IF NOT EXISTS `data_layer` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `layer_code` VARCHAR(20) NOT NULL COMMENT '分层编码',
    `layer_name` VARCHAR(50) NOT NULL COMMENT '分层名称',
    `layer_desc` VARCHAR(500) DEFAULT NULL COMMENT '分层描述',
    `layer_color` VARCHAR(20) DEFAULT '#1890ff' COMMENT '颜色标识',
    `sort_order` INT(11) DEFAULT 0 COMMENT '排序号',
    `status` VARCHAR(20) DEFAULT '0' COMMENT '状态 0=正常 1=停用',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_layer_code` (`tenant_id`, `layer_code`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数仓分层';

INSERT INTO `data_layer`
(`tenant_id`, `layer_code`, `layer_name`, `layer_desc`, `layer_color`, `sort_order`, `status`, `create_by`, `create_time`)
VALUES
('000000', 'ODS', '操作数据层', 'Operational Data Store，承接所有业务系统原始数据，保持与源系统一致的结构', '#909399', 1, '0', '-1', NOW()),
('000000', 'DWD', '明细数据层', 'Data Warehouse Detail，对ODS层数据进行清洗和规范化处理', '#409EFF', 2, '0', '-1', NOW()),
('000000', 'DWS', '汇总数据层', 'Data Warehouse Summary，按业务主题进行汇总加工', '#67C23A', 3, '0', '-1', NOW()),
('000000', 'ADS', '应用数据层', 'Application Data Store，面向应用和报表的集市层', '#E6A23C', 4, '0', '-1', NOW())
ON DUPLICATE KEY UPDATE
`layer_name` = VALUES(`layer_name`),
`layer_desc` = VALUES(`layer_desc`),
`layer_color` = VALUES(`layer_color`),
`sort_order` = VALUES(`sort_order`),
`status` = VALUES(`status`),
`update_time` = NOW();

CREATE TABLE IF NOT EXISTS `metadata_scan_log` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
    `ds_id` BIGINT(20) NOT NULL COMMENT '数据源ID',
    `ds_name` VARCHAR(100) DEFAULT NULL COMMENT '数据源名称',
    `ds_code` VARCHAR(50) DEFAULT NULL COMMENT '数据源编码',
    `scan_type` VARCHAR(20) DEFAULT 'ALL' COMMENT '扫描类型',
    `status` VARCHAR(20) DEFAULT 'RUNNING' COMMENT '状态',
    `total_tables` INT(11) DEFAULT 0 COMMENT '总表数',
    `success_count` INT(11) DEFAULT 0 COMMENT '成功数',
    `partial_count` INT(11) DEFAULT 0 COMMENT '部分成功数',
    `failed_count` INT(11) DEFAULT 0 COMMENT '失败数',
    `error_detail` TEXT DEFAULT NULL COMMENT '错误详情',
    `start_time` DATETIME DEFAULT NULL COMMENT '开始时间',
    `end_time` DATETIME DEFAULT NULL COMMENT '结束时间',
    `elapsed_ms` BIGINT(20) DEFAULT NULL COMMENT '耗时毫秒',
    `scan_user_id` BIGINT(20) DEFAULT NULL COMMENT '扫描触发用户ID',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `create_dept` BIGINT(20) DEFAULT NULL COMMENT '创建部门',
    `create_by` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ds_id` (`ds_id`),
    KEY `idx_status` (`status`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据扫描记录';
